### ISSUE TITLE
A long list of arguments will permanently break the UI

### ISSUE THREAD

**Issue by garrafote** [JetBrains/EzArgs#3]
The dropdown box will grow to accommodate the inputted list of arguments and will overflow to the left of the UI if the argument list is long enough. After growing in size it will never shrink back leaving the UI in a permanent broken state.

![image](https://user-images.githubusercontent.com/860128/117293534-6721ce80-ae69-11eb-998e-ee7649ff0120.png)

**Comment by DecoyRS** [comment]
It turned out to be a much harder problem than I've thought originally :(
Fixed in 0d2f55b9170a25c2e41630f80785a6b43dd34896 , will be available in 1.0.4 build, thought It'll be only compatible with Rider 4UE 2021.2+ (should be available today)

**Comment by chege011** [comment]
Still appear in 2022.2.3

**Comment by DecoyRS** [comment]
Hello folks!
I've made some changes to the EzArgs plugin:
 Added setting to limit the size of history of command line arguments (File | Settings | Tools | EzArgs)
 Added Expand button that will open a separate editor window that will be much more convenient to edit command line args. Every endline will be changed to a whitespace after closing a popup
 Fixed toolbar growing indefinitely 
In order to install new version, you need to go to
File | Settings | Plugins | "COG" on top | Manage Plugin repositories...
and add
https://plugins.jetbrains.com/plugins/alpha/list
you'll get an option to install an alpha build of the plugin.
I'd really appreciate if you could try it, share your experience if you have any artifacts or problems.
